/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_EccCurve_H_
#define	_EccCurve_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EccCurve {
	EccCurve_sgdsm2	= 0,
	EccCurve_nistP256	= 1,
	EccCurve_brainpoolP256rl	= 2
} e_EccCurve;

/* EccCurve */
typedef long	 EccCurve_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EccCurve;
asn_struct_free_f EccCurve_free;
asn_struct_print_f EccCurve_print;
asn_constr_check_f EccCurve_constraint;
ber_type_decoder_f EccCurve_decode_ber;
der_type_encoder_f EccCurve_encode_der;
xer_type_decoder_f EccCurve_decode_xer;
xer_type_encoder_f EccCurve_encode_xer;
per_type_decoder_f EccCurve_decode_uper;
per_type_encoder_f EccCurve_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EccCurve_H_ */
#include <asn_internal.h>
