/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 */

#ifndef	_HashedId8_H_
#define	_HashedId8_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HashedId8 */
typedef OCTET_STRING_t	 HashedId8_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HashedId8;
asn_struct_free_f HashedId8_free;
asn_struct_print_f HashedId8_print;
asn_constr_check_f HashedId8_constraint;
ber_type_decoder_f HashedId8_decode_ber;
der_type_encoder_f HashedId8_encode_der;
xer_type_decoder_f HashedId8_decode_xer;
xer_type_encoder_f HashedId8_encode_xer;
per_type_decoder_f HashedId8_decode_uper;
per_type_encoder_f HashedId8_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HashedId8_H_ */
#include <asn_internal.h>
