/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_IssuerID_H_
#define	_IssuerID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "CertificateDigest.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IssuerID_PR {
	IssuerID_PR_NOTHING,	/* No components present */
	IssuerID_PR_self,
	IssuerID_PR_certificateDigest
} IssuerID_PR;

/* IssuerID */
typedef struct IssuerID {
	IssuerID_PR present;
	union IssuerID_u {
		NULL_t	 self;
		CertificateDigest_t	 certificateDigest;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IssuerID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IssuerID;

#ifdef __cplusplus
}
#endif

#endif	/* _IssuerID_H_ */
#include <asn_internal.h>
