/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 */

#ifndef	_Payload_H_
#define	_Payload_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Opaque.h"
#include "SignedData.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Payload_PR {
	Payload_PR_NOTHING,	/* No components present */
	Payload_PR_unSecuredData,
	Payload_PR_signedData
} Payload_PR;

/* Payload */
typedef struct Payload {
	Payload_PR present;
	union Payload_u {
		Opaque_t	 unSecuredData;
		SignedData_t	 signedData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Payload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Payload;

#ifdef __cplusplus
}
#endif

#endif	/* _Payload_H_ */
#include <asn_internal.h>
