/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 */

#ifndef	_PublicVerifyKey_H_
#define	_PublicVerifyKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EccCurve.h"
#include "EccPoint.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PublicVerifyKey */
typedef struct PublicVerifyKey {
	EccCurve_t	 curve;
	EccPoint_t	 key;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PublicVerifyKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublicVerifyKey;

#ifdef __cplusplus
}
#endif

#endif	/* _PublicVerifyKey_H_ */
#include <asn_internal.h>
