/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SignedData_H_
#define	_SignedData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SignerInfo.h"
#include "TBSData.h"
#include "Signature.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignedData */
typedef struct SignedData {
	SignerInfo_t	 signer;
	TBSData_t	 tbs;
	Signature_t	 sign;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignedData;

#ifdef __cplusplus
}
#endif

#endif	/* _SignedData_H_ */
#include <asn_internal.h>
