/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 */

#ifndef	_TBSCert_H_
#define	_TBSCert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SubjectInfo.h"
#include "SubjectAttributes.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TBSCert */
typedef struct TBSCert {
	SubjectInfo_t	 subjectInfo;
	SubjectAttributes_t	 subjectAttributes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TBSCert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TBSCert;

#ifdef __cplusplus
}
#endif

#endif	/* _TBSCert_H_ */
#include <asn_internal.h>
