/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Uint16_H_
#define	_Uint16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Uint16 */
typedef long	 Uint16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Uint16;
asn_struct_free_f Uint16_free;
asn_struct_print_f Uint16_print;
asn_constr_check_f Uint16_constraint;
ber_type_decoder_f Uint16_decode_ber;
der_type_encoder_f Uint16_encode_der;
xer_type_decoder_f Uint16_decode_xer;
xer_type_encoder_f Uint16_encode_xer;
per_type_decoder_f Uint16_decode_uper;
per_type_encoder_f Uint16_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Uint16_H_ */
#include <asn_internal.h>
