/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Uint64_H_
#define	_Uint64_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Uint64 */
typedef unsigned long	 Uint64_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Uint64;
asn_struct_free_f Uint64_free;
asn_struct_print_f Uint64_print;
asn_constr_check_f Uint64_constraint;
ber_type_decoder_f Uint64_decode_ber;
der_type_encoder_f Uint64_encode_der;
xer_type_decoder_f Uint64_decode_xer;
xer_type_encoder_f Uint64_encode_xer;
per_type_decoder_f Uint64_decode_uper;
per_type_encoder_f Uint64_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Uint64_H_ */
#include <asn_internal.h>
