/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 */

#ifndef	_UnKnownLatitude_H_
#define	_UnKnownLatitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NinetyDegreeInt.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UnKnownLatitude */
typedef NinetyDegreeInt_t	 UnKnownLatitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnKnownLatitude;
asn_struct_free_f UnKnownLatitude_free;
asn_struct_print_f UnKnownLatitude_print;
asn_constr_check_f UnKnownLatitude_constraint;
ber_type_decoder_f UnKnownLatitude_decode_ber;
der_type_encoder_f UnKnownLatitude_encode_der;
xer_type_decoder_f UnKnownLatitude_decode_xer;
xer_type_encoder_f UnKnownLatitude_encode_xer;
per_type_decoder_f UnKnownLatitude_decode_uper;
per_type_encoder_f UnKnownLatitude_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UnKnownLatitude_H_ */
#include <asn_internal.h>
