/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "SPDU"
 * 	found in "SPDU.asn1"
 */

#ifndef	_UnKnownLongitude_H_
#define	_UnKnownLongitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NinetyDegreeInt.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UnKnownLongitude */
typedef NinetyDegreeInt_t	 UnKnownLongitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnKnownLongitude;
asn_struct_free_f UnKnownLongitude_free;
asn_struct_print_f UnKnownLongitude_print;
asn_constr_check_f UnKnownLongitude_constraint;
ber_type_decoder_f UnKnownLongitude_decode_ber;
der_type_encoder_f UnKnownLongitude_encode_der;
xer_type_decoder_f UnKnownLongitude_decode_xer;
xer_type_encoder_f UnKnownLongitude_encode_xer;
per_type_decoder_f UnKnownLongitude_decode_uper;
per_type_encoder_f UnKnownLongitude_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UnKnownLongitude_H_ */
#include <asn_internal.h>
